### ISSUE TITLE
Domoticz V3.9426 issue

### ISSUE THREAD

**Issue by deennoo** [febalci/DomoticzXiaomiPM2.5#1]
Hi there, looks to be a good work but i'm facinga probleme.

using domoticz : Domoticz V3.9426 and python 3.5.2

After installing your plugin and give right, i'm facing a seg fault.

have you try it on a last beta ?

**Comment by febalci** [comment]
It works on 4.9700 with python 3.6. You can search segfault issues on beta in domoticz forums. It is related mainly on python version issues.
