### ISSUE TITLE
Domoticz v3.9469 issue

### ISSUE THREAD

**Issue by bluedmx** [febalci/DomoticzXiaomiPM2.5#2]
Hi,
i have installed 2 py files and directory under plugins xiaomi folder. I have created a materials and after Domoticz is crashing. Need to delete the plugin resources to be able to launch again Domoticz.
Server : Raspberry PI 3B+ Raspbian Strench
Domoticz release : v3.9469
Best Regards.

**Comment by Nebukad93** [comment]
Hi,

Which Python version do you use now then ?

**Comment by jaapkoppejan** [comment]
I had the same issue: domoticz hangs upon installation of the plugin. Tried to remove python 3.5 and libpython3.5 but this did not bring any success.  

Maybe some more guidance / a small install manual would be helpful? Would love to see my sensor in Domoticz!

Domoticz release 3.9613 on raspberry pi 3b + raspbian stretch

**Comment by bluedmx** [comment]
Hi, my Python was 2.7.13. Finally, i  uninstalled the plugins Xiaomi PM because i need  more recent Python release for other customization.

**Comment by febalci** [comment]
I have it on domoticz 4.9700 stable on python 3.6.6 and it works well. On jessie raspbian domoticz plugins have serious issues. I suggest you use raspbian stretch. I happened to have segfault issues on jessie with python 3.4 with some plugins. Then i tried on stretch raspbian 2018-10-09 which has python 3.5.3 and it works fine.

**Comment by febalci** [comment]
Closing the issue since this is about Domoticz and python-raspbian issue.
